import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import TopNav from "@/components/TopNav";
import "./globals.css";

const fontAwesomeKitId = process.env.NEXT_PUBLIC_FONT_AWESOME_KIT_ID;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {!fontAwesomeKitId && (
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
            crossOrigin="anonymous"
            referrerPolicy="no-referrer"
          />
        )}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {fontAwesomeKitId && (
          <Script
            src={`https://kit.fontawesome.com/${fontAwesomeKitId}.js`}
            strategy="beforeInteractive"
            crossOrigin="anonymous"
          />
        )}
        <TopNav />
        {children}
      </body>
    </html>
  );
}
